// <auto-generated />
using DianaOsipovaKT_42_21.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DianaOsipovaKT_42_21.Migrations
{
    [DbContext(typeof(OsipovaDbContext))]
    [Migration("20241114144306_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DianaOsipovaKT_42_21.Models.EducationalSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("name")
                        .HasComment("Наименование дисциплины");

                    b.HasKey("Id")
                        .HasName("pk_educationalsubject_id");

                    b.ToTable("educationalsubject", (string)null);
                });

            modelBuilder.Entity("DianaOsipovaKT_42_21.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор преподавателя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age")
                        .HasComment("Возраст преподавателя");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("firstname")
                        .HasComment("Имя преподавателя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("lastname")
                        .HasComment("Фамилия преподавателя");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("middlename")
                        .HasComment("Отчество преподавателя");

                    b.HasKey("Id")
                        .HasName("pk_professor_id");

                    b.ToTable("professor", (string)null);
                });

            modelBuilder.Entity("DianaOsipovaKT_42_21.Models.Workload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasComment("Идентификатор нагрузки");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationalSubjectId")
                        .HasColumnType("int")
                        .HasColumnName("educationsubject_id")
                        .HasComment("Идентификатор дисциплины");

                    b.Property<int>("NumberOfHours")
                        .HasColumnType("int")
                        .HasColumnName("numberofhours")
                        .HasComment("Количество часов нагрузки");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int")
                        .HasColumnName("professor_id")
                        .HasComment("Идентификатор профессора");

                    b.HasKey("Id")
                        .HasName("pk_workload_id");

                    b.HasIndex("EducationalSubjectId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("workload", (string)null);
                });

            modelBuilder.Entity("DianaOsipovaKT_42_21.Models.Workload", b =>
                {
                    b.HasOne("DianaOsipovaKT_42_21.Models.EducationalSubject", "EducationalSubject")
                        .WithMany()
                        .HasForeignKey("EducationalSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_educationalsubject_id");

                    b.HasOne("DianaOsipovaKT_42_21.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_professor_id");

                    b.Navigation("EducationalSubject");

                    b.Navigation("Professor");
                });
#pragma warning restore 612, 618
        }
    }
}
